services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: shubhamwagh
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
    command: postgres -c 'max-connections=1000'

networks:
  db:
    driver: bridge

volumes:
  db: