services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: shubhamwagh
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  userinventory:
    container_name: userinventory
    image: shubhamwagh2544/userinventory
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
      SPRING_DATASOURCE_USERNAME: shubhamwagh
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  userinventory-react:
    container_name: userinventory-react
    image: shubhamwagh2544/userinventory-react
    build:
      context: react/react-frontend
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - userinventory
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: