services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: shubhamwagh
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
  userinventory:
    container_name: shubhams-userinventory
    image: shubhamwagh2544/userinventory
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    command:
      - --spring.datasource.url=jdbc:postgresql://db:5432/customer
      - --spring.datasource.username=shubhamwagh
      - --spring.datasource.password=password

networks:
  db:
    driver: bridge

volumes:
  db: